[workspace]
members = ["app"]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2024"
rust-version = "1.97"
license = "Apache-2.0"

[workspace.dependencies]
dioxus = { version = "=0.7.10", default-features = false, features = ["lib", "launch", "logger"] }
rusqlite = { version = "=0.40.2", features = ["bundled"] }
