[package]
name = "zeta-practice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true, features = ["fullstack", "router"] }

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server"]
